name: Trigger Repo B Workflow

on:
  schedule:
    - cron: '*/3 * * * *'  # ตั้งให้รันทุกวันเวลา 03:00 น. (UTC)

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send Dispatch Event
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
          https://api.github.com/repos/MadaMun/Lazy_Clear/dispatches \
          -d '{"event_type": "trigger_cron"}'
